<?xml version="1.0"?>
<package format="3">

  <name>robot_bringup</name>
  <version>0.1.0</version>

  <description>
    OpenRobotPlatform robot startup package.
  </description>

  <maintainer email="openrobotplatform@example.com">
    OpenRobotPlatform
  </maintainer>

  <license>Apache-2.0</license>


  <buildtool_depend>ament_cmake</buildtool_depend>


  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>


  <exec_depend>robot_description</exec_depend>
  <exec_depend>stereo_camera</exec_depend>
  <exec_depend>wt901_driver</exec_depend>
  <exec_depend>sensor_fusion</exec_depend>
  <exec_depend>serial_bridge</exec_depend>
  <exec_depend>mecanum_odometry</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
