ekf_filter_node:
  ros__parameters:
    frequency: 30.0

    sensor_timeout: 0.2

    two_d_mode: true

    transform_time_offset: 0.0
    transform_timeout: 0.1

    print_diagnostics: true
    debug: false

    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /wheel/odometry

    # 顺序：
    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    #
    # 当前只采用轮式里程计的 vx、vy。
    odom0_config: [
      false, false, false,
      false, false, false,
      true,  true,  false,
      false, false, false,
      false, false, false
    ]

    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data_raw

    # WT901当前没有姿态数据，只融合绕Z轴的角速度。
    imu0_config: [
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, true,
      false, false, false
    ]

    imu0_queue_size: 20
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false

    # 当前没有有效姿态，不能执行重力补偿。
    imu0_remove_gravitational_acceleration: false

    use_control: false
